GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE http://localhost:3001/todo/delete/647c6e4c23c8e51afe718887

###

PUT http://localhost:3001/todo/complete/647c62cd69419dc6c38d80ee